name: Deploy to Server via SSH

on:
  push:
    branches:
      - master  # or 'master'

jobs:
  test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: go-test
        run: |
          go test ./...

  deploy:
    needs: test
    name: Deploy to Remote Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Add Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy Application
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/ubuntu/simple-gin-app
            sudo docker stop ginapi || true
            sudo docker build -t ginapi .
            sudo docker run -d -p 8090:8090 ginapi
          EOF
        shell: bash
